### ISSUE TITLE
"short or no pull-up"

### ISSUE THREAD

**Issue by agrath** [bdlow/UT210E#1]
I've got a BP 3.6 and a brand new UT210
I've hooked up the BP via a SOIC8 clip double-checking the "v" output colours in the BP firmware match which SOIC pins I connected to and verified connection with a second multimeter.
When I have brought power & pull-up online with W/P in BP and then query i2c, I get "Warning: *short or no pull-up" back from BP
Not sure what I'm doing wrong, seems like everything is connected correctly unless I misread something (particularly around the additional ground required for reset)

The pictures of hooking up the BP are a bit unclear on the connection point between the SOIC8 clip and the hookup wires leading to BP, my SOIC clip is just naked with no header, and even if it had a header, I can't easily see which hookup wires are connected to which pins. 
Instead I've referred to the CZ1 image labelling the pins, and mapped these to my BP wire colours. 

Pictures attached:

The BP (power on / pull ups on)
![Image from iOS (30)](https://user-images.githubusercontent.com/78284/73495244-06f8dd00-441b-11ea-9eae-8242a2940323.jpg)

"v" output showing BP wire colours and voltages
![image](https://user-images.githubusercontent.com/78284/73495406-5dfeb200-441b-11ea-92c7-f09a735e4b10.png)

The BP clips:
![Image from iOS (31)](https://user-images.githubusercontent.com/78284/73495291-1d9f3400-441b-11ea-96f7-85a6463773b4.jpg)

```
1) BP:Brown[Wire]/Black[Clip] (GND) to Jumper:Black
2) BP:Red[Wire]/Yellow[Clip] (3.3V) to Jumper:Orange }      Same jumper as (3)
3) BP:Green[Wire]/Green[Clip] (VPU) to Jumper:Orange }      Same jumper as (2)
4) BP:Purple[Wire]/Green[Clip] (SCL) to Jumper:Purple
5) BP:Grey[Wire]/Yellow[Clip] (SDA) to Jumper:Blue
```

The other end of those jumpers going onto my clip:
![Image from iOS (30)](https://user-images.githubusercontent.com/78284/73495786-1cbad200-441c-11ea-9131-c9639ab3ed82.jpg)

Assuming the crystal is in the bottom right as per picture then the pins are stacked up as follows:

```
4) Blue (4th furthest from crystal, EEPROM side)  SDA
3) Purple SCL
2) Brown WP (see below, this jumps from one side of the clip to the other)
1) Orange (closest to crystal, EEPROM side) 3.3V
```

Then on the other side of the clip:
```
8) Brown
7) NC
6) Black
5) NC
```

As all the EEPROM grounds on this side are tied together, this means that my jumper wires for Brown (EEPROM/CZ1 WP) and Black (BP GND) are tied together, 
This also (on the PCB) connects to VSS on the CZ1 header based on a multimeter probe test.

SOIC8 clip on the chip
![Image from iOS (18)](https://user-images.githubusercontent.com/78284/73496464-8687ab80-441d-11ea-9e3d-3e0570384fe7.jpg)

I have to shuffle it a bit to get it to contact (as well as nudge the capacitors) but I verified connection before bringing the BP up by using my other multimeter in beep mode confirming that the CZ1 pins mapped to my expected BP clips.

**Comment by af3556** [comment]
Hi @agrath, is this still a problem? I'll have some time over this weekend to take a closer look and reproduce on my device if you need.

**Comment by agrath** [comment]
Hey @bdlow Ben 
I never solved this problem.
A contact had an eeprom flasher that I used to make the configuration changes so I'm actually sorted on flashing it - but not with the BP.
I'm in Auckland, NZ and we're in full lockdown so I don't have access to my UT210E or my BP (both are at my office) so if you need me to check anything on my setup that will be a bit difficult right now!

**Comment by af3556** [comment]
I just modded another meter per the Bus Pirate method in this repo, worked a-ok.

I suspect the issue you saw was bad connections: I just compared your BP pin state (v command) to what should be expected: yours was different/wrong: you had SCA and SCL low (L), they should have been high (H).
