### ISSUE TITLE
ErrE shown after EEProm Flashing

### ISSUE THREAD

**Issue by Kleinerben** [bdlow/UT210E#2]
Dear Folks, maybe sorry for this question, but im new to this.

I did the mod via Arduino and everythings worked fine. I added 6200 counts. But i recognized, that i didnt measure between 6,2 and 9,7 Volts anymore. So restored the original eprom, and i works fine again. 

After that i just wanted to flash those mods in the eprom i really need. But no i cant read it out anymore. Also when i plug in the Battery and try to turn it on 

"ErrE"

comes up in the Display. 

How can i reset it..? What can i do to get access to the eeprom?

regards

**Comment by af3556** [comment]
Hi Burnst,

Odd that the meter wouldn't read above 6.2V (6200 counts). It's possible you have a newer revision of the ASIC? As to the ErrE - I've not seen that issue, so can't offer any specific suggestions I'm afraid. I presume you're already done the basic stuff like double-check all connections, etc.

For example, this person got an ErrE but had a bad connection:
https://www.eevblog.com/forum/testgear/a-look-at-the-uni-t-ut210e/msg1272710/?topicseen#msg1272710

I suggest heading on over to the eevblog forum, perhaps asking on the above thread.

If you find out the cause of the "can't measure above 6.2V" issue, please do let me know and I'll add it to the info in this repo :-)

Rgds,
Ben

**Comment by Kleinerben** [comment]
Dear Ben,

ben here;)..

.. i flashed the original Eeprom and i could measure the voltage between 6.2 and 9.7 vollts correct again. I could switch it on and measured 7v correct.

i guess i did too much mods, so i decided to mod Just those things i really need... But before i started, i recognized that a pin became loose and i resoldered it again. But finally then i couldnt get any connection to the eeprom on the same way i did it before.

Also i couldnt turn it on again. Just  'ErrE' is blinking in the Display...:(...

U mean the eevblog someone can help me?

Regards

Ben

**Comment by af3556** [comment]
> Also i couldnt turn it on again. Just 'ErrE' is blinking in the Display...:(...
> U mean the eevblog someone can help me?

My guess is that you may have damaged something, or have a bad connection or short circuit. The people on eevblog may have some insight on troubleshooting or repairing the meter; if you do a search on that forum you'll find other people who have also reported "ErrE" - you might be able to find what they did to fix their issue.
