### ISSUE TITLE
ut210D

### ISSUE THREAD

**Issue by sims-60** [bdlow/UT210E#3]

**Comment by sims-60** [comment]
will it work with the ut210d?

**Comment by af3556** [comment]
I'm not familiar with the UT210D; you could open it up and check the main IC, if it's DTM0660L or DM1106EN then the info here may be applicable. If you don't yet have a 210D, then I'd head over to https://www.eevblog.com/forum/testgear/ and do some research and ask if I couldn't find an answer.
