### ISSUE TITLE
wrong values in table?

### ISSUE THREAD

**Issue by Whisperflux** [bdlow/UT210E#4]
First, thanks for your work to collect the information here.

Since i have no experience in coding and i have a 210d instead of a "e"version i am very carefully checking what is the same and what not, what can be changed and what not and i came across the table.
for changing to 6000 counts.
__________________
Address | OEM Value | Description
-- | -- | --
0x10-0x11 | 0x1770 | full range (6000d = 0x1770; 8000d = 0x1F40)
__________________

In other info like the 210e-Calculator here on github from adlerweb, with not loading even a file, and just click the black button to see at end of page the values changed, one sees
adres 10 original value 70, modded 70 
adres 11 original value 17, modded 17

these values on adres 10 and 11 as 70 and 17 instead of 17 and 70 are also seen at the EEV blog.

So you might want to change these in the table.
thanks.

**Comment by af3556** [comment]
Hi @tegenlicht, I believe you may have missed that 16-bit values are stored in the EEPROM in what's called "little endian" order. That is, the 16-bit register value 1770 (hex) would be stored in EEPROM as 70 in the first/lower address, and 17 in the second/higher address.

I've added additional notes on this, and here's a straightforward example of endianness: https://www.geeksforgeeks.org/little-and-big-endian-mystery/

Note that not all meters/devices will use little-endian, it depends on the processor/ASIC. Some more complex, longer-word (64/128 bit) processors, or those optimised for network data, can use really weird and even mixed bit-ordering.

**Comment by Whisperflux** [comment]
Thanks for your reply.
And no i didn't missed that...i was simply just unable to see.....still have so much to learn:))
Thanks for your explanation and link! 
grtz Luc
