### ISSUE TITLE
The UT210E could have a different eeprom installed

### ISSUE THREAD

**Issue by Feuerstahl** [bdlow/UT210E#5]
The UT210 not only has the DM24C02A EEprom installed, it could be a different one (T24C02A).
In my case the manufacturer used the T24C08A which has 1024 bytes..
Fortunately they use the same EEPROM-Addresses.
So if the EEPROM goes bad you can use the same size, a bigger one or a different manufacurer to be back in game.

In the attachments, you can see the Addresses since 0x0100 are empty.

Greetings
Feuerstahl 

![UT210E _EEprom_dump_1](https://user-images.githubusercontent.com/59896256/211168217-f2a985ee-2aa9-4cac-aa1c-93641ba39e96.PNG)
![UT210E _EEprom_dump_2](https://user-images.githubusercontent.com/59896256/211168222-3583027a-2536-45d6-8680-451fc4337ee9.PNG)

**Comment by af3556** [comment]
Thanks @Feuerstahl, good to know; a sensible call from Uni-T supply chain wise: I haven't compared the specs between the common DM24C02A and T24C02A but I presume the only real requirement is >= 256 bytes (i.e. speed is probably not a concern).
